### ISSUE TITLE
Cannot start frontend

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/qs-web2023#21]
When trying this on a separate LAN, following instructions in the README, started the backend with no problem.  Trying to access the backend URL (`http://localhost:3001`), browser receives: `Cannot GET /`

Continuing with frontend, `npm start` fails with:

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:434:10)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:466:5
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:327:12
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:386:16)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:418:10
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:293:13
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.0
```

**Comment by prjemian** [comment]
This was with requirement `nodejs <18`.  Next, setting requirement `nodejs = 16`.

**Comment by prjemian** [comment]
Similar

```

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:434:10)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:466:5
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:327:12
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:386:16)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:418:10
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/webpack/lib/NormalModule.js:293:13
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/prjemian/Documents/projects/BCDA-APS/gemqsweb/frontend/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by prjemian** [comment]
### `./backend/.env`

```env
PORT=3001
API_URL=http://localhost:60610
```

and verified the bluesky queueserver _is_ running and backend started with `npm start`.

### `./frontend/.env`

```env
BACKEND_URL=http://localhost:3001
```

**Comment by prjemian** [comment]
Check the development system for version info.  Testing on external system was too big a first step to be successful.

**Comment by prjemian** [comment]
FYI, console from when backend started:

```
(gemqsweb) prjemian@arf:~/.../gemqsweb/backend$ npm start

> backend@1.0.0 start
> node server.js

PORT: 3001
API_URL: http://localhost:60610
🚀 Server running on http://localhost:3001
```
